# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# Check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2

# Mod Properties
mod_version=1.0.0
maven_group=com.shoto290.reignofalpha
archives_base_name=reign-of-alpha

# Dependencies
fabric_version=0.133.4+1.21.8
loom_version=1.11-SNAPSHOT