package com.solegendary.reignofnether.player;

// actions that can be done to Player entities serverside
public enum PlayerAction {
    START_RTS_EVERYONE,
    CANCEL_START_RTS_EVERYONE,
    TELEPORT,
    ENABLE_ORTHOVIEW,
    DISABLE_ORTHOVIEW,
    START_RTS_VILLAGERS,
    START_RTS_MONSTERS,
    START_RTS_PIGLINS,
    START_RTS_SANDBOX,
    DEFEAT,
    VICTORY,
    ADD_RTS_PLAYER,
    REMOVE_RTS_PLAYER,
    RESET_RTS,
    RESET_RTS_HARD,
    SYNC_RTS_GAME_TIME,
    LOCK_RTS,
    UNLOCK_RTS,
    ENABLE_START_RTS,
    DISABLE_START_RTS,
    DISABLE_RTS_SYNCING,
    ENABLE_RTS_SYNCING,
    SYNC_BEACON_OWNER_TICKS
}
