package com.solegendary.reignofnether.gamerules;

public enum GameruleAction {
    SET_LOG_FALLING,
    SET_NEUTRAL_AGGRO,
    SET_MAX_POPULATION,
    SET_UNIT_GRIEFING,
    SET_PLAYER_GRIEFING,
    SET_IMPROVED_PATHFINDING,
    SET_GROUND_Y_LEVEL,
    SET_FLYING_MAX_Y_LEVEL,
    SET_ALLOW_BEACONS,
    SET_PVP_MODES_ONLY,
    SET_BEACON_WIN_MINUTES,
    SET_SLANTED_BUILDING,
    SET_ALLOWED_HEROES,
    SET_LOCK_ALLIANCES,
    SET_SCENARIO_MODE
}
