package com.solegendary.reignofnether.sounds;

public enum SoundAction {
    STOP_SOUND,
    USE_PORTAL,
    RANDOM_CAVE_AMBIENCE,
    ALLY,
    CHAT,
    ENEMY,
    BELL,
    BEACON_ACTIVATE,
    BEACON_DEACTIVATE,
    BEACON_AMBIENT,
    LEVEL_UP,
    BLOODLUST,
    HEROISM,
    WRETCHED_WRAITH_ATTACK_QUIET,
    WRETCHED_WRAITH_ATTACK_LOUD,
    WRETCHED_WRAITH_TELEPORT_START,
    WRETCHED_WRAITH_TELEPORT_END,
    WRETCHED_WRAITH_BLIZZARD,
    WILDFIRE_MOLTEN_BOMB,
    WILDFIRE_SCORCHING_GAZE_START,
    WILDFIRE_SCORCHING_GAZE_END,
    WILDFIRE_SOULS_AFLAME,
    PIGLIN_MERCHANT_LOOT_EXPLOSION,
    ENCHANT,
    FORGE_ARMOUR
}
