package com.solegendary.reignofnether.scenario;

public enum ScenarioAction {
    SET_ROLE_STARTING_FOOD,
    SET_ROLE_STARTING_WOOD,
    SET_ROLE_STARTING_ORE,
    SET_ROLE_FACTION_VILLAGER,
    SET_ROLE_FACTION_MONSTER,
    SET_ROLE_FACTION_PIGLIN,
    SET_ROLE_FACTION_NEUTRAL,
    SET_ROLE_NAME,
    SET_ROLE_TEAM_NUMBER,
    SET_ROLE_NPC,
    SET_UNIT_ROLE,
    SET_BUILDING_ROLE,
    SET_SCENARIO_NAME,
    SAVE_SCENARIO,
    LOAD_SCENARIO_ROLE
}
